[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin@wso2.com"
password = "admin"
create_admin_account = true

[tenant_mgt]
enable_email_domain = true
disable_email_domain_validation = true

[user_store]
type = "database_unique_id"
username_java_script_regex = '^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$'
username_java_regex = '^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}'

[database.identity_db]
url = "jdbc:postgresql://identity-test.cvroo3yhsnfj.eu-west-1.rds.amazonaws.com:5432/identity_db"
username = "wso2carbon"
password = "wso2carbon"
driver = "org.postgresql.Driver"

[database.identity_db.pool_options]
validationQuery = "SELECT 1"

[database.shared_db]
url = "jdbc:postgresql://identity-test.cvroo3yhsnfj.eu-west-1.rds.amazonaws.com:5432/shared_db"
username = "wso2carbon"
password = "wso2carbon"
driver = "org.postgresql.Driver"

[database.shared_db.pool_options]
validationQuery="SELECT 1"

[database.user]
url = "jdbc:postgresql://identity-test.cvroo3yhsnfj.eu-west-1.rds.amazonaws.com:5432/shared_db"
username = "wso2carbon"
password = "wso2carbon"
driver = "org.postgresql.Driver"

[database.user.pool_options]
validationQuery = "SELECT 1"

[bps_database.config]
url = "jdbc:postgresql://identity-test.cvroo3yhsnfj.eu-west-1.rds.amazonaws.com:5432/bps_db"
username = "wso2carbon"
password = "wso2carbon"
driver = "org.postgresql.Driver"

[database.bps_database.pool_options]
validationQuery = "SELECT 1"

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

[event.default_listener.identity_mgt]
priority= "50"
enable = false

[event.default_listener.governance_identity_mgt]
priority= "95"
enable = true

[event.default_listener.governance_identity_store]
priority= "97"
enable = true

[identity_mgt.user_onboarding]
enable_email_verification = true
lock_on_creation = false

[identity_mgt.user_self_registration]
allow_self_registration = true 
expiry_time = "1440"

[authentication.consent]
prompt = false

[oauth]
prompt_consent = false
openid_skip_user_consent = false

[admin_service.wsdl]
enable = true

[output_adapter.email]
from_address = "noreply@protel.net"
username = "noreply@protel.net"
password = "no_reply123!"
hostname = "smtp.office365.com"
port = 587
enable_start_tls = true
enable_authentication = true

[cors]
allow_generic_http_requests = true
allow_any_origin = false
allowed_origins = [
    "http://localhost:3001"
]
allow_subdomains = false
supported_methods = [
   "GET",
   "POST",
   "HEAD",
   "OPTIONS",
   "PUT",
   "PATCH",
   "HEAD",
   "DELETE",
   "PATCH"
]
support_any_header = true
supported_headers = []
exposed_headers = [ "Location" ]
supports_credentials = true
max_age = 3600
tag_requests = false

[user_store.properties]
is_bulk_import_supported  =  true

[server.file_upload]
file_size_limit = "100"